version: '3.9'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      FLASK_APP: "app"  
      FLASK_ENV: "development"
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5002
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "catalogo_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
